#!/bin/sh

usage() {
	cat << EOF
    startke < options >
            x11             launch Xorg KDE
            wayland         launch Wayland KDE 
EOF
}

case $1 in
    wayland) /usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland ;;
    x11) startx /usr/bin/startplasma-x11 ;;
    *) usage ;;
esac

